name: Build Docker Image
on:
  push:
    branches: ['main']
    tags: ['**']
jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Build mappings
        id: mappings
        run: |
          registry=docker.pkg.github.com
          #registry=ghcr.io # Will be enabled when GitHub Container Regsitry is released
          echo "::set-output name=registry::$registry"

          base="$registry/mathieu-bour/php-dev/php-dev"

          if [[ $GITHUB_REF == *"tags"* ]]; then
            tag=${GITHUB_REF/refs\/tags\//}
            image="$base:$tag"
          else
            hash=${GITHUB_SHA:0:7}
            image="$base:$hash"
          fi

          echo "::set-output name=image::$image"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ${{ steps.mappings.outputs.image }} .
      - name: Push Docker image
        run: |
          echo "${{ secrets.GH_TOKEN }}" | docker login ${{ steps.mappings.outputs.registry }} -u mathieu-bour --password-stdin
          docker push ${{ steps.mappings.outputs.image }}